import React from 'react';
import { Send } from 'lucide-react';
import { ContactChip } from './ContactChip';
import { useTypewriterStream } from '../hooks/useTypewriterStream';

interface GmailComposeCardProps {
  active: boolean;
  onSend: () => void;
}

export const GmailComposeCard: React.FC<GmailComposeCardProps> = ({
  active,
  onSend,
}) => {
  const recipient = 'david@company.com';
  const targetSubject = 'Project update and Thursday sync';
  const targetBody = `Hi David,\n\nThe designs look great. Let's sync Thursday to review the prototypes.\n\nBest`;

  const {
    displayedText: subjectText,
    setDisplayedText: setSubjectText,
    isTyping: isTypingSubject,
  } = useTypewriterStream({
    text: targetSubject,
    speed: 22,
    active,
  });

  const {
    displayedText: bodyText,
    setDisplayedText: setBodyText,
  } = useTypewriterStream({
    text: targetBody,
    speed: 16,
    active: active && !isTypingSubject,
  });

  return (
    <div
      onClick={(e) => e.stopPropagation()}
      className="w-full h-full flex flex-col justify-between text-left select-text bg-[#16181F]/95"
    >
      {/* Header Bar */}
      <div className="flex items-center justify-between px-6 py-3.5 bg-[#1F222B] border-b border-white/[0.08] rounded-t-[22px]">
        <div className="flex items-center gap-3">
          {/* Gmail Logo SVG */}
          <div className="w-6 h-6 flex items-center justify-center shrink-0">
            <svg viewBox="0 0 24 24" className="w-5 h-5">
              <path
                fill="#EA4335"
                d="M12 13.5L1.5 5.25V18c0 .83.67 1.5 1.5 1.5h18c.83 0 1.5-.67 1.5-1.5V5.25L12 13.5z"
              />
              <path
                fill="#FBBC05"
                d="M22.5 4.5H19.5v7.5l3-2.25V6c0-.83-.67-1.5-1.5-1.5z"
              />
              <path
                fill="#34A853"
                d="M1.5 4.5h3v7.5l-3-2.25V6c0-.83.67-1.5 1.5-1.5z"
              />
              <path
                fill="#4285F4"
                d="M19.5 4.5L12 10.5 4.5 4.5H1.5c-.24 0-.46.06-.66.16L12 13.5l11.16-8.84c-.2-.1-.42-.16-.66-.16h-3z"
              />
            </svg>
          </div>
          <span className="text-sm font-semibold text-white tracking-wide">
            New Message
          </span>
        </div>
      </div>

      {/* Recipient Row */}
      <div className="flex items-center gap-4 px-6 py-2.5 border-b border-white/[0.06] bg-[#16181F]">
        <span className="text-sm font-medium text-gray-400 w-8 select-none">To</span>
        <ContactChip email={recipient} name="David Miller" />
      </div>

      {/* Subject Row */}
      <div className="flex items-center px-6 py-2.5 border-b border-white/[0.06] bg-[#16181F]">
        <input
          type="text"
          value={subjectText}
          onChange={(e) => setSubjectText(e.target.value)}
          placeholder="Subject"
          className="w-full bg-transparent text-sm text-gray-100 placeholder-gray-500 font-medium outline-none focus:text-white"
        />
      </div>

      {/* Body Area */}
      <div className="flex-1 px-6 py-3.5 bg-[#16181F] overflow-hidden">
        <textarea
          value={bodyText}
          onChange={(e) => setBodyText(e.target.value)}
          placeholder="Type your message..."
          rows={5}
          className="w-full h-full bg-transparent text-sm text-gray-200 placeholder-gray-500 font-normal outline-none resize-none leading-relaxed [scrollbar-width:none] [&::-webkit-scrollbar]:hidden focus:text-white"
        />
      </div>

      {/* Bottom Footer / Action Button */}
      <div className="flex items-center justify-between px-6 py-3 bg-[#1A1C24] border-t border-white/[0.08] rounded-b-[22px]">
        <span className="text-xs text-gray-400 font-medium">
          Draft generated by Mavis · Click Send
        </span>
        <button
          onClick={(e) => {
            e.stopPropagation();
            onSend();
          }}
          className="inline-flex items-center gap-2 px-6 py-2 rounded-full bg-gradient-to-r from-[#2B7FFF] to-[#1E6FE8] hover:from-[#388BFF] hover:to-[#2B7FFF] active:scale-95 text-white font-semibold text-sm shadow-[0_4px_16px_rgba(43,127,255,0.4)] hover:shadow-[0_6px_20px_rgba(43,127,255,0.6)] transition-all duration-150 cursor-pointer"
        >
          <span>Send</span>
          <Send className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
};
